### PR TITLE
Adds denylist

### PR DESCRIPTION
**Pull request by vpetersson**
Adds denylist to config.

### CODE REVIEW

**Review by metawake — APPROVED** [review]
looks good syntactically

**Comment by shawaj** [comment]
Once merged, can you test on testnet to make sure the config pulls through correctly @NebraLtd/tech-support ?

Before we merge to production.

**Comment by shawaj** [comment]
@vpetersson only thing I'm wondering is why we have a different number of lines to upstream...

https://github.com/helium/miner/blob/master/config/sys.config

**Comment by vpetersson** [comment]
It's because they are using two files and reference each other whilst we have a single file with everything.

**Comment by shawaj** [comment]
> @vpetersson only thing I'm wondering is why we have a different number of lines to upstream...
> 
> https://github.com/helium/miner/blob/master/config/sys.config

Actually, I think I know why.... It's the garbage collection

**Comment by shawaj** [comment]
This is the other line that's different:

https://github.com/NebraLtd/hm-block-tracker/blob/8300402f056f44e91a80e0b5775cbe4440f96b1c/config.template#L87

**Comment by shawaj** [comment]
This is where they removed it upstream https://github.com/helium/miner/commit/3d813c25f734147216bb49cce3b458fb85720e5e

**Pull request merged**
