### PR TITLE
update: snapshotter config for GA 2022.06.09.0

### PR DESCRIPTION
**Pull request by marvinmarnold**
**Issue**

- Link:
- Summary: Enable mux for snapshotter. Configs for miners in fleet have already been updated

**How**
https://engineering.helium.com/2022/06/10/miner-hotspot-release.html

**Screenshots**

**References**
Follow-up to: https://github.com/NebraLtd/hm-block-tracker/pull/102/files

**Checklist**

- [ ] Tests added
- [ ] Cleaned up commit history (rebase!)
- [ ] Documentation added
- [ ] Thought about variable and method names

### CODE REVIEW

**Comment by KevinWassermann94** [comment]
@marvinmarnold We've already pushed this to production here: https://github.com/NebraLtd/hm-block-tracker/pull/102

**Review by KevinWassermann94 — APPROVED** [review]

**Comment by marvinmarnold** [comment]
That updated the config that gets pushed to our fleet. This is for the config used by the snapshotter instance itself which I also updated to the newest GA.

**Comment by KevinWassermann94** [comment]
@marvinmarnold Yeah sorry, I've just realized that

**Comment by marvinmarnold** [comment]
Yea, this repo is confusing.

**Pull request merged**
