### PR TITLE
release(prod): Snapshotter configs for 2022.06.09.0

### PR DESCRIPTION
**Pull request by marvinmarnold**
**Issue**

- Link:
- Summary: Enable mux for snapshotter. Configs for miners in fleet have already been updated

**How**
https://engineering.helium.com/2022/06/10/miner-hotspot-release.html

**Screenshots**

**References**
Follow-up to: https://github.com/NebraLtd/hm-block-tracker/pull/103

**Checklist**

- [ ] Tests added
- [ ] Cleaned up commit history (rebase!)
- [ ] Documentation added
- [ ] Thought about variable and method names

### CODE REVIEW

**Review by KevinWassermann94 — APPROVED** [review]

**Comment by shawaj** [comment]
@KevinWassermann94 @marvinmarnold do we need to push this to production to avoid issues?

**Comment by marvinmarnold** [comment]
@shawaj this PR is really documentation only. The actual snapshotter instance is still manually deployed. I already updated the running instance with these changes. We should still merge this though, thanks for the bump.

**Comment by shawaj** [comment]
Ah ok, didn't realise it was manual. No probs 😁

**Review by pritamghanghas — APPROVED** [review]

**Comment by pritamghanghas** [comment]
I will raise PR for any further changes if required. we can merge this.

**Pull request merged**
